# Generated by Django 4.1.5 on 2023-01-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblCustomer',
            fields=[
                ('customer_email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_nickname', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_title', models.CharField(max_length=20)),
                ('review_grade', models.IntegerField()),
                ('review_contents', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jiningApp.tblcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='TblShop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=20)),
                ('shop_site_x', models.CharField(max_length=30)),
                ('shop_site_y', models.CharField(max_length=30)),
                ('shop_review_grade', models.IntegerField()),
                ('shop_review_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TblTasteInfo',
            fields=[
                ('tastekey', models.AutoField(db_column='tasteKey', primary_key=True, serialize=False)),
                ('tastevalue', models.CharField(db_column='tasteValue', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TblTaste',
            fields=[
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='jiningApp.tblshop')),
                ('info1', models.CharField(max_length=20)),
                ('info2', models.CharField(max_length=20)),
                ('info3', models.CharField(max_length=20)),
                ('info4', models.CharField(max_length=20)),
                ('info5', models.CharField(max_length=20)),
                ('info6', models.CharField(max_length=20)),
                ('info7', models.CharField(max_length=20)),
                ('info8', models.CharField(max_length=20)),
                ('info9', models.CharField(max_length=20)),
                ('info10', models.CharField(max_length=20)),
                ('info11', models.CharField(max_length=20)),
                ('info12', models.CharField(max_length=20)),
                ('info13', models.CharField(max_length=20)),
                ('info14', models.CharField(max_length=20)),
                ('info15', models.CharField(max_length=20)),
                ('info16', models.CharField(max_length=20)),
                ('info17', models.CharField(max_length=20)),
                ('info18', models.CharField(max_length=20)),
                ('info19', models.CharField(max_length=20)),
                ('info20', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TblReviewImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=100)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jiningApp.tblreview')),
            ],
        ),
        migrations.AddField(
            model_name='tblreview',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jiningApp.tblshop'),
        ),
        migrations.CreateModel(
            name='TblOwner',
            fields=[
                ('owner_email', models.CharField(db_column='Owner_email', max_length=40, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(db_column='Owner_name', max_length=20)),
                ('owner_nickname', models.CharField(db_column='Owner_nickname', max_length=20, unique=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jiningApp.tblshop')),
            ],
        ),
    ]
