# Generated by Django 4.1.5 on 2023-01-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiningApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblowner',
            old_name='shop',
            new_name='shop_id',
        ),
        migrations.RenameField(
            model_name='tbltaste',
            old_name='shop',
            new_name='shop_id',
        ),
        migrations.RenameField(
            model_name='tbltasteinfo',
            old_name='tastekey',
            new_name='taste_key',
        ),
        migrations.RenameField(
            model_name='tbltasteinfo',
            old_name='tastevalue',
            new_name='taste_value',
        ),
    ]
