# Generated by Django 4.1.5 on 2023-01-13 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jiningApp', '0003_alter_tblowner_owner_email_alter_tblowner_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblowner',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_owner', to='jiningApp.tblshop'),
        ),
        migrations.AlterField(
            model_name='tblreview',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='jiningApp.tblcustomer'),
        ),
        migrations.AlterField(
            model_name='tblreview',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_review', to='jiningApp.tblshop'),
        ),
        migrations.AlterField(
            model_name='tblreviewimage',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='jiningApp.tblreview'),
        ),
        migrations.AlterField(
            model_name='tbltaste',
            name='shop_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jiningApp.tblshop'),
        ),
    ]
